### ISSUE TITLE
Feature request: add palettes from the {khroma} package

### ISSUE THREAD

**Issue by elipousson** [mtennekes/cols4all#12]
I'm a big fan of the palettes from the [khroma](https://packages.tesselle.org/khroma/index.html) package and would love to see them added to cols4all. The description notes that most of the palettes included with the package are:

- Distinct for all people, including colour-blind readers,
- Distinct from black and white,
- Distinct on screen and paper,
- Matching well together,
- Citable and reproducible.

The package also includes some scientific thematic schemes (geologic timescale, land cover, FAO soils, etc.) that may not be color-blind safe so may not be appropriate for inclusion in this package.

**Comment by mtennekes** [comment]
Thanks!

As far as I know, the palettes of khroma consist of two series: from Paul Tol and from Fabio Crameri.
These are already contained in cols4all. The former are the series `tol` (extracted directly from Paul Tol's site), and the latter from the R package `scico`.

Please let me know what palette/functions you still miss. (Please make sure to get the latest GH version of cols4all)

**Comment by Nowosad** [comment]
@mtennekes I would suggest to keep the `"scico"` name (it is fine).

**Comment by elipousson** [comment]
It is great to know that you already have these in the package! If you can keep this open for another day or two, I'll double-check and make sure I can find everything that I was looking for using the `"scico"` name. I think keeping the package focused on accessibility makes a ton of sense and would push to add the scientific thematic themes that are not.

**Comment by mtennekes** [comment]
Thank, @elipousson yes please take your time.
