### ISSUE TITLE
Confusion lines

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/cols4all#16]
Is there an R implementation of the CIE horseshoe and the confusion lines? (@nowosad and @zeileis)
I am looking for something like this:

![](https://www.color-blind-glasses.com/wp-content/uploads/2022/05/confusion-lines.jpg)

My aim is to show the confusion lines and to show the colours of a certain palette as dots.

So far, I managed to create an xyY plot (https://github.com/mtennekes/cols4all/blob/devel2/sandbox/chromaticity.R):

![image](https://user-images.githubusercontent.com/2444081/189930369-c0f99349-27bc-47f8-b6ec-8b5ab2903732.png)

but it only contains the colours inside the sRGB gamut. Probably the black borders are caused by artefacts due to the algorithm I used (e.g. to calculate the max Y for a given x,y pair).

**Comment by zeileis** [comment]
Same here. Don't you have to go through the sRGB gamut ultimately because that is what is used by R's graphics system?

**Comment by mtennekes** [comment]
Thx! Yes, it is indeed limited by the sRGB gamut. Not sure how the images above are created, probably with clipping.
Well, at least a colleague found the coordinates for the confusion lines in the xy plane: https://www.researchgate.net/figure/Confusion-lines-and-types-of-dichromatism-Dichromatic-confusion-lines-represented-for_fig1_322712348

That we be sufficient, so you can expect an R implementation shortly :-)

**Comment by zeileis** [comment]
If I'm reading the meta-information correctly, then the PNG in the first post also uses sRGB. So I would suspect that this is an "emulation" or "illustration" rather than a faithful display of the colors.
