### ISSUE TITLE
Almost ready for CRAN release: feedback wanted

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/cols4all#18]
Hi all (incl @helgasoft, @mpetroff, @Nowosad, @Robinlovelace, @zeileis, @fmegahed, @mputs),

I've update the cols4all gui. Please take a look if you have time:

```r
# colorspace 2.1 required:
install.packages(https://rdrr.io/r/utils/install.packages.html)("colorspace", repos = "https://R-Forge.R-project.org")
remotes::install_github("mtennekes/cols4all")
library(cols4all)
c4a_gui()
```

cols4all is still maturing, but I believe/hope this version is good enough for the first CRAN release.

Feedback is welcome

**Comment by zeileis** [comment]
...which reminds me that I should really get out the new `colorspace` version. I've been delaying this because I wanted to find the time to write a proper blog post explaining the changes which I haven't done yet. Martijn, which timeline are you aiming for?

**Comment by mtennekes** [comment]
This year, but no rush :-)

**Comment by zeileis** [comment]
OK, good. I'll try to move it up on my (too long) to-do list. Feel free to ping me when you move closer to the release and it still isn't out...

**Comment by mtennekes** [comment]
cols4all still uses the old WCAG algorithm.for the contrast ratio, but apparently there is a new algorithm out there (great!). That should be easy to incorporate. Do you know if the algorithm is still under development or the R implementation (or both)?

**Comment by fmegahed** [comment]
Hi all,

cols4all new GUI has been updated at https://cols4all.fsb.miamioh.edu/ . I
look into the rest of the code and see if I can provide suggestions.


-----------------------------------------------------------------------
If you would like to discuss any additional information, please feel free
to schedule a meeting with me <https://calendly.com/fmegahed>.

Best regards,
Fadel

Fadel Megahed
Endres Associate Professor
Farmer School of Business
Miami University (OH)
Email: ***@***.***
Office: (513) 529-4185
Web: Official Miami Website
<http://miamioh.edu/fsb/directory/?up=/directory/megahefm> | Google Scholar
<https://scholar.google.com/citations?user=6CTlKGMAAAAJ&hl=en> |
ResearchGate <https://www.researchgate.net/profile/Fadel_Megahed> | GitHub
<https://github.com/fmegahed/>

**Comment by fmegahed** [comment]
I have now loaded the png package and made sure that I have updated to the latest version of the package. There are still three errors that I am getting:

- In the contrast pane, "unable to open inst/img/Richard-Anuszkiewicz-_Plus-Reversed.png"
- In the 3D Blues pane, "unable to open inst/img/floating_rings.png"
- In the application pane, "REAL() can only be applied to a 'numeric', not a 'integer'"

**Comment by mtennekes** [comment]
The first 2 issues should be solved. However, the 3rd is cryptical. Hopefully it should work, and if not, I will commit some print statements in order to find the bug.

**Comment by Nowosad** [comment]
Hi @mtennekes -- I used the app version provided by @fmegahed (thanks!). My comments

- Some icons are broken:

![image](https://user-images.githubusercontent.com/3457131/204103733-33bab1e4-d2b9-4683-978b-2710a974cece.png)

- There is a text "See tab vividness and harmony", but such tab does not exist
- I am not sure how to interpret some of the information in the color blind friendliness tab (and other tabs, as well). Also, I just by accident discovered that I can click on some plots to select colors for an analysis.

**Comment by mtennekes** [comment]
Thx @fmegahed for the update and @Nowosad for the feedback. My answers:

* Could you report which icons are broken (and which OS/browser you're using). I guess it is OS/browser specific, because it looks fine here (macOS/safari).
* It was an old tab name. It's now HCL Analysis. Will update
* Good point. I'm struggling what to do to make it intuitive for most users. In an earlier version I had lot's of explanation text, but in my experience no one reads text in visualizations / dashboards. I hope that the dashboard is intuitive by itself and perhaps a sentence or two. 

There is also the vignette (draft): https://github.com/mtennekes/cols4all/blob/main/vignettes/cols4all-intro.Rmd which should explain most of the GUI. And indeed, you can click on the 'matrix plots' to select colours.

Suggestions welcome. For those of you who have time, we could also arrange a Zoom call to discuss these topics.

**Comment by Nowosad** [comment]
Maybe you could add a few short gifs/figures to the vignette? They may explain somethings quicker...

Btw my OS/browser is Fedora/Firefox.

**Comment by mtennekes** [comment]
Good idea, I had the same idea. Can you already make any sense of the GUI? I'm just wondering how self-explanatory it is.

Which icons are broken in your case @Nowosad ? This is what I see (macOS left, Windows right):

<img width="2186" alt="Screenshot 2022-12-07 at 13 06 32" src="https://user-images.githubusercontent.com/2444081/206175889-60ade141-f1e3-4c22-ae6f-18f8b364b8fe.png">

**Comment by Nowosad** [comment]
Fedora/Firefox:

![image](https://user-images.githubusercontent.com/3457131/206238456-4188c95a-7b79-4aa0-ba48-8f3d190054df.png)

Fedora/Brave:

![image](https://user-images.githubusercontent.com/3457131/206238637-8fc54b10-7657-4a6b-868c-f5e8c897a057.png)

**Comment by mtennekes** [comment]
Thanks @Nowosad Should be better know.

I also changed "Harmony" to "Equity". The idea behind this indicator is that colors are equally important, in other words no color should stand out more than others. The terms "color balance" and "color harmony" are already occupied in literature. Also, "equality" suggests that colours are the same, but they are not (only chroma and luminance are about the same). Do you think this is a good term?

The icons for "vivid" could perhaps be improved. This indicator tells if a palette contains only 'pastel' colors (colors with chroma lower than a threshold), or if a palette contains at least one vivid color (with a chroma value larger than a threshold). Now they are indicated with a snowflake and pair of sunglasses respectively, but there could be better icons...

**Comment by mpetroff** [comment]
Sorry I didn't get a chance to look at this earlier. I'm currently on my way to Antarctica and will have limited internet access while there, but I was just able to take a quick look while I still have semi-decent internet access while in New Zealand.

I'm not familiar with R packaging, but I had to manually install the `kableExtra` package to get `cols4all` to install, so I think it probably shouldn't just be a suggested dependency. To get the GUI to work, I also had to install the `shiny`, `shinyjs`, and `colorblindcheck` packages, so I would recommend explicitly stating that these needed to be installed for the GUI in the installation section of the readme.

The new tabs are nice additions; I particularly like the distance matrices.

On the _HCL Analysis_ and _Contrast_ tabs, I would change the "Use original colors" checkboxes to "Use optical illusion's original colors" as it took me a while to figure out which original colors they were referring to.

> cols4all still uses the old WCAG algorithm.for the contrast ratio, but apparently there is a new algorithm out there (great!). That should be easy to incorporate. Do you know if the algorithm is still under development or the R implementation (or both)?

While everyone can agree that the old WCAG contrast algorithm is extremely flawed, the development process of the new algorithm is a mess. The person developing the new algorithm claims to have done experiments to back up the new algorithm but has not published any details that I've seen as to the experimental design or results, at least not to the extent that would come remotely close to passing peer review at a reputable journal. Furthermore the person behind the new algorithm seems to interpret any requests for such details as personal attacks and responds in kind, creating a hostile environment (see, e.g., [w3c/silver](https://github.com/w3c/silver) issue 574). The leadership for the W3C working group seems to have done nothing about the hostile environment, despite what I'd consider to be clear violations of the W3C code of conduct by the algorithm developer. It is a really unfortunate situation.

> I also changed "Harmony" to "Equity"

I'm not sure I agree with this word choice, as _equity_ generally has to do with things being fair or just, although I see your reasoning about the colors being "fair" in the sense that some don't unfairly grab one's attention. It's hard to condense the concept of similar visual weight down to a single word. Other options I came up with are _homogeneity_, _uniformity_, and _similitude_, but I don't think they quite fit either.

**Comment by mtennekes** [comment]
Thanks for you excellent suggestions @mpetroff !

1. Good point. It is a devils dilemma: when stating these packages as requires dependencies will let the dependencies tree of packages that will use cols4all grow (e.g. tmap). But as you mention, from a users perspective it would be better. Alternatively, we could split the package into a base package ("cols4allBase") and an add-on package ("cols4all") that includes the GUI and also ggplot2 scales. I don't see any downsides for that other than having another package. What do you think, other R users (@zeileis @Robinlovelace @Nowosad )?
2. That is indeed unfortunate. I will stick to the WCAG for the time being.
3. Hmm, maybe "fairness" would actually be good one! (Homogeneity and uniformity may suggest that colors are the same).

Have a good time in Antarctica and say hi to the penguins!

**Comment by zeileis** [comment]
Two quick comments:

1. I personally dislike multiple packages because it increases the work and the complexity of maintenance. To overcome potential problems with the installation, I would typically explain on the web page that `install.packages("cols4all", dependencies = TRUE)` should be run prior to using the GUI.
2. I was aware that the there is some controversy around the APCA algorithm but not regarding the extent. Not good! In any case, I had implemented the APCA algorithm in the `contrast_ratio()` function in `colorspace` after Lisa Muth had "advertised" it in her blog. However, I didn't make it the default, yet, because it was unclear where this is going exactly. See <http://colorspace.R-Forge.R-project.org/reference/contrast_ratio.html> for the current state. I plan to update the function when there is official progress towards WCAG3.  Luckily the implications for statistical graphics are not as fundamental as for typesetting in HTML.

**Comment by mtennekes** [comment]
Thanks for your input. For now, I decided to keep having just one package, but to make life easier I've added a "The packages ... are required. Do you want to install them?" question.

GUI updates:

* Added info-animations (tab page 2-5). Are they clear? Text suggestions welcome! (They don't always render well in dark mode).
* Changed "harmony" to "fair(ness", and also changed the icons.
* Improved the references column headers
* Sequential palettes can now be sorted by 'Hue mean'. Handy if you are looking for a specific hue. I renamed the column "Hues" to "Hue type" to prevent confusion. Diverging palettes can be sorted by hue mean L and R, and by luminance mid. If there are any other useful ways of sorting palettes, let me know.

**Comment by mtennekes** [comment]
@fmegahed Could you update the gui on the server? Seems to be offline. Thanks!
@zeileis How is colorspace 2.1 going?

The current version is ready to go, but feedback is always welcome.

**Comment by zeileis** [comment]
Thanks for your patience, `colorspace` 2.1-0 is now out on CRAN. Now I just have to find the time to write a short blog post about it...

**Comment by mtennekes** [comment]
Awesome, thanks!

**Comment by mtennekes** [comment]
Just submitted to CRAN, but it seems that kableExtra should be in the imports:


On both Debian and Windows the same false positive?

We see during installation:

** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'cols4all':
  .onLoad failed in loadNamespace() for 'cols4all', details:
   call: loadNamespace(x)
   error: there is no package called 'kableExtra'


Having "kableExtra" in Suggests is not sufficient and you may need to
declare it in Imports (or LinkingTo or Depends) as you use it in .onLoad
and hence it has to be a strong dependency.

Please fix and resubmit.

Best,
Uwe Ligges


I don't understand why. It is not such big a deal, but will not help to keep the dependencies trees small.

**Comment by zeileis** [comment]
You cannot use the package without `kableExtra` when it is used in `.onLoad()`. Thus, it needs to be a strong dependency because you cannot do anything without it. So either you find a way to avoid (or delay) the usage of `kableExtra` in `.onLoad()` or you need to make it a strong dependency (probably `Depends`).

**Comment by mtennekes** [comment]
Ah, I see, thanks! Yes, I've used it to define certain options (e.g. tooltips). But that can indeed be delayed.

**Comment by zeileis** [comment]
Very good! That's what I thought/hoped :nerd_face:

**Comment by mtennekes** [comment]
On CRAN so closing this.

(@fmegahed if you have time: could you update the server)
