### ISSUE TITLE
cols4all installation failed

### ISSUE THREAD

**Issue by Pigeongeon** [mtennekes/cols4all#19]
> ###
> install.packages("cols4all")
Warning in install.packages :
  package ‘cols4all’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

> ###
> devtools::install_local("C:/R/R-4.2.2/library/cols4all-main", force = TRUE)
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\wpz\Data\TEMP\RtmpYxwhKs\file3c24ff95289\cols4all-main/DESCRIPTION' ...
─  preparing 'cols4all':
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a 'data/datalist' file should be added
─  building 'cols4all_0.4.tar.gz'
   
* installing *source* package 'cols4all' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'colorspace' 2.0-3 is being loaded, but >= 2.1 is required
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'cols4all'
* removing 'C:/R/R-4.2.2/library/cols4all'
Warning message:
In i.p(...) :
  installation of package ‘C:/wpz/Data/TEMP/RtmpYxwhKs/file3c2428401844/cols4all_0.4.tar.gz’ had non-zero exit status

> if (!requireNamespace("BiocManager", quietly = TRUE))
+   install.packages("BiocManager")
> BiocManager::install("cols4all")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://mirrors.sjtug.sjtu.edu.cn/cran/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31 ucrt)
Installing package(s) 'cols4all'
Old packages: 'boot', 'cli', 'foreign', 'isoband', 'Matrix', 'nlme', 'purrr', 'xfun'
Update all/some/none? [a/s/n]: 
n
Warning message:
package ‘cols4all’ is not available for Bioconductor version '3.16'

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 

> ###
> BiocManager::install("cols4all")
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://mirrors.sjtug.sjtu.edu.cn/cran/

Bioconductor version 3.16 (BiocManager 1.30.19), R 4.2.2 (2022-10-31 ucrt)
Installing package(s) 'cols4all'
Old packages: 'boot', 'cli', 'foreign', 'isoband', 'Matrix', 'nlme', 'purrr', 'xfun'
Update all/some/none? [a/s/n]: 
n
Warning message:
package ‘cols4all’ is not available for Bioconductor version '3.16'

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by Pigeongeon** [comment]
> # install.packages("devtools")
> remotes::install_github("mtennekes/cols4all")
Downloading GitHub repo mtennekes/cols4all@HEAD
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\wpz\Data\TEMP\RtmpYxwhKs\remotes3c247931471c\mtennekes-cols4all-5351160/DESCRIPTION' ... 
─  preparing 'cols4all':
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a 'data/datalist' file should be added
─  building 'cols4all_0.4.tar.gz'
   
* installing *source* package 'cols4all' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'colorspace' 2.0-3 is being loaded, but >= 2.1 is required
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'cols4all'
* removing 'C:/R/R-4.2.2/library/cols4all'
Warning message:
In i.p(...) :
  installation of package ‘C:/wpz/Data/TEMP/RtmpYxwhKs/file3c2439a6524a/cols4all_0.4.tar.gz’ had non-zero exit status

**Comment by mtennekes** [comment]
You'll need to run:

install.packages(https://rdrr.io/r/utils/install.packages.html)("colorspace", repos = "https://R-Forge.R-project.org")

which installs the dev version (2.1) of `colorspace`

`cols4all` is scheduled for CRAN release mid January

**Comment by Pigeongeon** [comment]
@mtennekes
I have successfully installed the r package, thank you for your help!

**Comment by Pigeongeon** [comment]
I have successfully installed the r package, thank you for your help!


| |
wenpeizhen1996
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/29/2022 03:54 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [mtennekes/cols4all] cols4all installation failed (Issue #19) |

You'll need to run:

install.packages(https://rdrr.io/r/utils/install.packages.html)("colorspace", repos = "https://R-Forge.R-project.org")

which installs the dev version (2.1) of colorspace

cols4all is scheduled for CRAN release mid January

**Comment by mtennekes** [comment]
You're welcome! (If you have any suggestions for the package let us know:-))

**Comment by dongdongdamowang** [comment]
> You'll need to run:
> 
> install.packages([https://rdrr.io/r/utils/install.packages.html)("colorspace](https://rdrr.io/r/utils/install.packages.html)(%22colorspace)", repos = "https://R-Forge.R-project.org")
> 
> which installs the dev version (2.1) of `colorspace`
> 
> `cols4all` is scheduled for CRAN release mid January

HI, I can not run : install.packages((https://rdrr.io/r/utils/install.packages.html)(%22colorspace)", repos = "https://r-forge.r-project.org/")  .How could I do?
My issue:
<html>
<body>


> remotes::install_github("mtennekes/cols4all", dependencies = TRUE) Downloading GitHub repo mtennekes/cols4all@HEAD ── R CMD build ───────────────────────────────────────────────────────────────────────────── ✔  checking for file ‘/home/data/t030305/Rtmp/RtmpoGihoD/remotes23449b5f32a3d5/mtennekes-cols4all-4f5f907/DESCRIPTION’ ... ─  preparing ‘cols4all’: ✔  checking DESCRIPTION meta-information ─  checking for LF line-endings in source and make files and shell scripts ─  checking for empty or unneeded directories    Removed empty directory ‘cols4all/build’ ─  looking to see if a ‘data/datalist’ file should be added ─  building ‘cols4all_0.6.tar.gz’     Installing package into ‘/home/data/t030305/R/x86_64-pc-linux-gnu-library/4.1’ (as ‘lib’ is unspecified) * installing *source* package ‘cols4all’ ... ** using staged installation ** R ** inst ** byte-compile and prepare package for lazy loading Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :    namespace ‘colorspace’ 2.0-3 is being loaded, but >= 2.1 is required Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace Execution halted ERROR: lazy loading failed for package ‘cols4all’ * removing ‘/home/data/t030305/R/x86_64-pc-linux-gnu-library/4.1/cols4all’ Warning message: In i.p(...) :   installation of package ‘/home/data/t030305/Rtmp/RtmpoGihoD/file23449b9d89488/cols4all_0.6.tar.gz’ had non-zero exit status
--
 
> | >
>


</body>
</html>

**Comment by mtennekes** [comment]
Hi @dongdongdamowang you should be able to install it directly from CRAN: `install.packages("cols4all")`

**Comment by dongdongdamowang** [comment]
I run： install.packages("cols4all"). But it also met these error.


Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘colorspace’ 2.0-3 is being loaded, but >= 2.1 is required
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package ‘cols4all’
* removing ‘/home//R/x86_64-pc-linux-gnu-library/4.1/cols4all’
Warning in install.packages :
  installation of package 'cols4all' had non-zero exit status

**Comment by mtennekes** [comment]
You should remove the old version of colorspace (2.0-3), but you can only do that if it is not used (so a fresh R session is required). When you run `install.packages("cols4all")` next, it should automatically install colorspace 2.1 from CRAN
