### ISSUE TITLE
"key" for symbols on GUI overview table

### ISSUE THREAD

**Issue by Aariq** [mtennekes/cols4all#21]
Would be nice to be able to hover over the symbols on the overview table in the GUI to get a short description of what they mean.  Either that or a small legend somewhere would be useful.  Love the table though!

**Comment by mtennekes** [comment]
Good suggestion, thx!

**Comment by mtennekes** [comment]
Hi @Aariq the tooltip hover was already there. However, sometimes for some reason it only works after a mouse click (no matter where).

Could you test it?

**Comment by Aariq** [comment]
Yes, I did get the tooltip hover to work.  Not sure if I just didn't notice it before, or if it was that it didn't work until a mouseclick.  The tooltips are exactly what I was looking for.
