### ISSUE TITLE
Specify color for NA values

### ISSUE THREAD

**Issue by sw-rifai** [mtennekes/cols4all#22]
Is there a way to specify the color for NA values instead of the associated value in c4a_na?

If not, I think this would be a very useful feature (particularly for making maps). 
All in all, a great package!

**Comment by mtennekes** [comment]
Good question!
 
In the current approach, the color for NA is part of the 'palette data' that is constructed with `c4a_data` and loaded into cols4all with `c4a_load`.

For palettes that are already loaded in cols4all, it is not straightforward yet to change any of the palette specifications (such as color for NA). The easiest way is:

```r
dat = c4a_sysdata_export()
dat$data$na[dat$data$fullname == "misc.okabe"] = "#FF0033"
c4a_sysdata_import(dat)
```

Perhaps we could think about a more useful friendlier way. E.g. `c4a_modify("misc.okabe", xNA = "#FF0033")`. What do you think @sw-rifai ?

**Comment by sw-rifai** [comment]
Thanks @mtennekes for the quick response. I see your point about the
palette data, but thank you for the handy trick to update the color table.
Agreed that a function like c4a_modify would be fantastic! I could imagine
that being also useful for when a specific discrete class needs to be
highlighted with a manually specified color.

**Comment by mtennekes** [comment]
c4a_modify implemented (as well as c4a_duplicate to keep the original)
if anything doesn't work well, let me know
