### ISSUE TITLE
Pleaseeeee add this amazing color palette :)

### ISSUE THREAD

**Issue by ScottCoffin** [mtennekes/cols4all#31]
If you have literally nothing else to do, it would be super cool if you could add [these palettes](https://github.com/an-bui/calecopal) to your amazing package! They are some of the most aesthetically pleasing color palettes I know of. 

Thank you!

**Comment by mtennekes** [comment]
I assume they are adopted by [`paletteer`](https://github.com/EmilHvitfeldt/paletteer) ? If so: I'll share the data from all `paletteer` palettes so they can be loaded in cols4all.

**Comment by ScottCoffin** [comment]
Yes it appears like paletteer has them! Thank you!!!
