### ISSUE TITLE
Upcoming CRAN release 0.8

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/cols4all#34]
Many new features:

* main table much faster
* colors can be sorted
* cyclic palettes
* matplotlib and poweri series added
* HCL space in 3d
* properties improved
* new vignette (also journal submission) 

Also a few breaking changes:

* Previously, I standardised the sequential palettes: if they vary in luminance, I ordered the colors from light to dark. However, now I take all the palettes as they are (since color sorting can now be done in the gui). Only for categorical palettes, I remove blacks (e.g. from okabe). The implication is the `"hcl.blues3"` will run from dark to light. In tmap4, this is already taken into account.
* I've moved the palettes from the 'viridis' series to their origin 'matplotlib', or 'seaborn'.

There are two reverse dependencies: **`sits`** and **`stgam`**. Could you please check if all is good regarding your packages  @lexcomber and @gilbertocamara ?

FYI: @zeileis @olivroy @helgasoft @Nowosad @Robinlovelace @fmegahed @mpetroff 
Questions or suggestions welcome

Planning to host the GUI on my employers website, but feel free to host it anywhere else!

**Comment by olivroy** [comment]
Hi @mtennekes ! I may have one suggestion. Due to https://github.com/r-tmap/tmap/commit/f84c89ede1e341adf8161e597887fa284874918d, I had to add colorblindcheck to Imports in tmap. https://github.com/r-tmap/tmap/commit/f890abd6416f0c5005faeb3dbb2ee68696a5e43e

I wonder if it should be in Imports in cols4all?

**Comment by mtennekes** [comment]
Good question @olivroy 

I can do that, but the downside is that `colorblindcheck` suggests `rcartocolor` which suggests `ggplot2`, so the whole tidyerse will be installed as well. Not a great deal of course, but I'd like to keep the package as lightweight as possible regarding the depends and imports. `colorblindcheck` is only used when new palettes are added, which is not an everyday task.

The tmap commit you referred to is used to use the new cols4all palettes. However, once cols4all is on CRAN, I'll remove that part again and set cols4all (>= 0.8) in the imports.

**Comment by olivroy** [comment]
Okay, sounds good! Wanted to make sure there was a way to avoid colorblindcheck in tmap imports!

**Comment by Nowosad** [comment]
(Also: if needed I can slim the colorblindcheck dependencies)

**Comment by olivroy** [comment]
It is just that we are approaching the 20 Imports limit set by CRAN in tmap https://github.com/r-tmap/tmap/blob/master/DESCRIPTION

**Comment by Nowosad** [comment]
@mtennekes -- the table speed improvement is great! It is much smoother now.

**Comment by olivroy** [comment]
@mtennekes I haven`t tested the release candidate, but is this problem fixed in the dev version of the shiny app `cols4all::c4a_gui("seq")`

![image](https://github.com/user-attachments/assets/4df4e74e-1145-4934-8200-cca607360f12)

I wonder if it were possible to fix before releasing?

**Comment by mtennekes** [comment]
I recall this vaguely @olivroy : when was this issue addressed the first time?
I can't reproduce so probably already fixed

**Comment by mtennekes** [comment]
Almost ready for CRAN.

@olivroy minor thing: in the GH pages, I saw that the vignette is placed under the menu item 'get started'. https://mtennekes.github.io/cols4all/

Do you know where that is specified? I'd like to change it, because in the README is already a 'getting started' section, and I see the vignette more of a in-depth (methodologically) article.

**Comment by olivroy** [comment]
@mtennekes Simply rename the vignette to another name. (I actually renamed it in https://github.com/mtennekes/cols4all/pull/28/commits/9704b2fa3a68854cd09186c9ca071ec9294109ad specifically for that) The vignette {packagename}.Rmd automatically gets mapped as a Get Started vignette.

**Comment by mtennekes** [comment]
Thx @olivroy 

- [ ] Vignette now under 'Articles' menu: perfect:-)
- [ ] References to figures and tables working
- [ ] Equations broken again.... 

I've added `pkgdown: as_is: true` in the header to get the references working but not equations are not rendering.

Do you have any idea? Perhaps adding mathjaxr to the suggests? (https://stackoverflow.com/questions/66030234/equation-numbering-in-r-package-vignette)

https://github.com/r-lib/pkgdown/issues/323

**Comment by mtennekes** [comment]
This maybe useful: https://github.com/orgs/community/discussions/22525#discussioncomment-3237176
Now figuring out where to find the default template...

**Comment by olivroy** [comment]
In pkgdown ref page: https://pkgdown.r-lib.org/articles/customise.html?q=math#math-rendering

**Comment by mtennekes** [comment]
Didn't succeed yet... My current yaml head is:

```yml
output: 
  bookdown::html_vignette2:
pkgdown:
  as_is: true
template:
  math-rendering: mathjax
```

also tested `katex` (https://github.com/mtennekes/cols4all/commit/fd923c3db52822e9034ee4d6e19ff7022984297d#diff-470f1790e2f74710495ba0384cff36f3988c143bbae75646a61903da7a92c2d2R8) and ```math_method: mathml``` before, but without success. Any help would be greatly appreciated (@Nowosad @olivroy) Or do you know of any other vignette on GitHub pages that uses math?

**Comment by Nowosad** [comment]
Locally, a version without any changes to the header works fine (the website vignette has both equations and references)


```
---
title: "Analysing and comparing color palettes with cols4all"
output: 
  bookdown::html_vignette2
bibliography: '`r system.file("cols4all.bib", package="cols4all")`'
csl: "`r system.file('ieee.csl', package = 'cols4all')`"
vignette: >
  %\VignetteIndexEntry{cols4all: analysing and comparing color palettes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

**Comment by mtennekes** [comment]
Solved via https://github.com/mtennekes/cols4all/pull/35

**Comment by mtennekes** [comment]
Submitted to CRAN.

@olivroy Sorry to bother you again, but due to the CRAN policy of < 5MB,  I had to move the vignette and its figures to vignette/articles (web-only). However, I don't know what urls I should use for the figures in README. The figures are loaded in https://github.com/mtennekes/cols4all when I set the urls to `vignettes/articles/x.jpg`, but https://mtennekes.github.io/cols4all/index.html expects `articles/x.jpg`. Is there a trick to get them both working?

**Comment by mtennekes** [comment]
0.8 on CRAN, vignettes online, and paletteer data added as download:

```r
paletteer = readRDS(gzcon(url("https://mtennekes.github.io/cols4all/paletteer.rds")))

c4a_sysdata_import(paletteer)
c4a_gui()
```

The app is relatively fast for 2000+ palettes.
I will write a short vignette about this.

**Comment by Robinlovelace** [comment]
This is really great, thank you Martijn. Tested the other day with my colleague @wangZhao0217 and it helped us choose a palette.
