### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by os2137** [mtennekes/cols4all#5]
after installing devtools and running this code devtools::install_github("mtennekes/cols4all")
I am getting the following error on my windows system
Error: Failed to install 'unknown package' from GitHub:
HTTP error 401.
Bad credentials

Rate limit remaining: 47/60
Rate limit reset at: 2022-02-24 12:56:24 UTC

**Comment by mtennekes** [comment]
Seems to be a GH issue, see e.g. https://github.com/r-lib/remotes/issues/638 and https://github.com/r-lib/remotes/issues/659
Afaik not related to cols4all.
