### ISSUE TITLE
Package functions not loading

### ISSUE THREAD

**Issue by famfigueiredo** [mtennekes/cols4all#6]
Hey @mtennekes,

Very cool (and welcome) package.

I ran into an issue where running `cols4all::c4_palettes(type = 'seq', series = 'tol')` yields:
`Error: 'c4_palettes' is not an exported object from 'namespace:cols4all'`

I can launch the GUI, so the package is loaded. However, I am not able to do anything else.
What am I doing wrong?

**Comment by mtennekes** [comment]
Thanks for letting me know @famfigueiredo 
It should be working now, if not, please reopen this issue.

**Comment by mtennekes** [comment]
Where did you get that code from? Probably an old version, because it contains a typo: if could be c4**a**_palettes:

`c4a_palettes(type = "seq", series = "tol")`

**Comment by famfigueiredo** [comment]
I am so sorry I missed that typo! It is working fine now. Thank you, @mtennekes.
