### ISSUE TITLE
Testing 1 2 3

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/cols4all#9]
Hi all (in particular @helgasoft, @mpetroff, @nowosad, @Robinlovelace, @zeileis, and @fmegahed,

The package is imho ready for CRAN, but still in development phase (so version < 1.0).
I am still learning about color theory, so indicators may change, as well as the palettes that I recently added (seq/div and biv). Moreover, we are still unsure what the best way is to calculate distance matrices for color vision deficiency. Distances are calculated upstream (`colorspace` and `colorblindcheck`), but are used to calculate the color-blind-friendliness scores.

Please let me know if you find any issues.

Best,

Martijn

PS. I still have to document the used quality indicators. Hopefully we can open a discussion what good indicators are and which parameters to use.

**Comment by mtennekes** [comment]
Thx @Nowosad 

1. Good point. Maybe that is better indeed. The reason I initially went for `bivu` was that it was called "bivariate-uncertainty", and that `bivd` might be confusing since it could also stand for "bivariate-diverging". (See below)
2. Yes, indeed. I am not a Shiny tiger, so PRs are welcome. Will also take a look myself. Recently I saw `colorspace::hcl_wizard`, which looks more professional (at least the source code), so maybe I can learn from that. It also has a 'dark mode', which works better (i.e. also the buttons selectizeinputs are updated).

Regarding 1: what do you think of the name `bivc`? Brewer has two variants for columns: categorical and diverging. However, I noticed that categorical with more than 2 hues does not work for people with CVD. Therefore I only have one variant: an `n=3` diverging palette for columns and a sequential scale for rows. I named it `bivc`, but this may misleading (?) Alternatively, we could use `bivd`, but this would be a good candidate for the current `bivu` (your first remark).

What is your take on this?

**Comment by zeileis** [comment]
Regarding `hcl_wizard()`: That is some Reto-magic. He would say that he also isn't overly familiar with `shiny` but he clearly has done solid work here. If you have any concrete questions, you can contact him directly or I can pass the question on to him.

**Comment by Nowosad** [comment]
@mtennekes I have thought about the abbreviations for some time, but I still do not have a perfect solution. 

One idea I have is to rename current `bivu` to `bivl` (bivariate (sequential x less saturated)), and use `bivd` for the diverging one.

**Comment by mtennekes** [comment]
Thx @Nowosad !

Also related: currently I have put seq x cat and seq x div into one type (currently called `bivc`). It would probably be better to have them as separate types (`bivc` and `bivd`), just to be complete, although I would not recommend any seq x cat palette, simply because they are not color blind friendly.

We can indeed use `bivl` for the seq x desaturated palettes. A downside is that "l" may also be associated with "light". Alternatively, we can use `bivg` where the g stands for gra/eyscale, but that is also not perfect...

Meanwhile, I have updated the GUI: smaller fonts and no more columns inside the input panel. Suggestions and PRs are welcome!

@zeileis thanks for the implementation of colorspace convention in linear RGB (gamma=FALSE) into `colorspace`. When is the next CRAN release of `colorspace` expected?

**Comment by zeileis** [comment]
I haven't scheduled a next release, yet. I'm also not fully sure that the current implementation is the most natural one. And the default for `gamma` is least clear to me.

All of these are indicators that it might help to wait and discuss a bit more before carving stuff into stone (which is what a CRAN release would do). But it would be good not to wait too long.

**Comment by Robinlovelace** [comment]
Sorry I've not had a chance to look at this yet, will try to take a peak asap but don't wait for me.

**Comment by mtennekes** [comment]
No worries and thanks for your help @Robinlovelace I'm still finetuning bits and pieces, so it can wait. 

From now on I'll use the `devel` branch for the latest version and the master for a more stable version. Probably it is best to test the `devel` branch.

**Comment by mtennekes** [comment]
I've updated the GUI recently. The input widgets should be better, especially for smaller screens. 
I've also improved the bivariate palettes.

Testers go ahead! (@Robinlovelace @Nowosad @zeileis @helgasoft )

**Comment by Nowosad** [comment]
Looks good!

**Comment by fmegahed** [comment]
Hi all,

@mtennekes , I was finally able to host the app on our university server. It is available at <http://cols4all.fsb.miamioh.edu/cols4all/>.  

To create the app, I have created the following two files:

- [app.R](https://raw.githubusercontent.com/fmegahed/cols4all_hosting/main/app.R), which loads the package from GitHub and install/load the dependencies.  
- [run_app.R](https://raw.githubusercontent.com/fmegahed/cols4all_hosting/main/run_app.R), which utilizes on [Shiny's runApp()](https://shiny.rstudio.com/reference/shiny/0.14/runApp.html) to run the app by running the app.R file 


@Robinlovelace @Nowosad @zeileis @helgasoft, if you can test the hosted app as well that would be awesome!!

**Comment by zeileis** [comment]
I took it for a very quick spin, looks good! 👍

**Comment by helgasoft** [comment]
Hosted app is great, love it 🏆

**Comment by Nowosad** [comment]
I cannot see the app neither on my laptop nor smartphone). I assume this my local issue (?) -- maybe some of you know how to fix it...

![image](https://user-images.githubusercontent.com/3457131/165922752-74cc706d-0c48-48fc-9113-8182bf13b49f.png)

**Comment by fmegahed** [comment]
@Nowosad , it is working for me right now. Would you please retry it? 

Please use http::// and not https://

**Comment by zeileis** [comment]
I double checked and it works on my phone and laptop. But it's important to include the trailing slash at the end after "cols4all". Without that the page is not found...

**Comment by mtennekes** [comment]
I've started a issue-list, see https://github.com/mtennekes/cols4all/issues/13

@fmegahed The server is up again, but I cannot log-in to RStudio yet(?).
